title: Emoji calendar
description: Emoji Calendar
baseurl: ''
url: ''

image:
  logo: /assets/et8h.png
  large: /assets/et8h.png
  background: /assets/background.png

yandex_metrika: 56873668
google_analytics: UA-117276892-3

markdown: kramdown
timezone: Europe/Moscow
encoding: utf-8
permalink: pretty
future: true
exclude: ['LICENSE', 'CHANGELOG.md']
