title: Emoji Calendar
description: >
  A calendar is a system of organizing days for social, religious, commercial or administrative purposes. This is done by giving names to periods of time, typically days, weeks, months and years. A date is the designation of a single, specific day within such a system. A calendar is also a physical record (often paper) of such a system. A calendar can also mean a list of planned events, such as a court calendar or a partly or fully chronological list of documents, such as a calendar of wills.
baseurl: ''
url: ''

default_lang: en

twitter: tophackr_com
image:
  logo: /assets/et8h.png
  large: /assets/et8h-large.png

yandex_metrika: 56873668
google_analytics: UA-117276892-3

markdown: kramdown
timezone: Europe/Moscow
encoding: utf-8
permalink: pretty
future: true
plugins:
  - liquid-md5
  - jekyll-sitemap
exclude: ['LICENSE', 'CHANGELOG.md', 'README.md', 'emojicalendar.png']
